name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        include-prerelease: True
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Build package
      run: dotnet pack --configuration Release
    - name: Publish nuget package
      run: dotnet nuget push "Common/bin/Release/**/*.nupkg" -k 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 -s "https://nuget.pkg.github.com/matthiasffm"
