name: package .NET

on:
  workflow_dispatch:

jobs:
  package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0'
        include-prerelease: True

    - name: Build package
      run: dotnet pack Common/Common.csproj -c Release --include-source --include-symbols -v d

    - name: Adding GitHub nuget source
      run: dotnet nuget add source --username matthiasffm --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/matthiasffm/index.json"

    - name: Publish nuget package
      run: dotnet nuget push "Common/bin/Release/**/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate