name: package .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build package
      run: dotnet pack --configuration Release

    - name: Setting nuget source
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/matthiasffm/index.json"

    - name: Publish nuget package
      run: dotnet nuget push "Common/bin/Release/**/*.nupkg" --skip-duplicate --no-symbols true
